# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            Artem Lavrov
tagline:          'Random thoughts'
description:      'My personal blog'
url:              https://artlavrov.github.io
baseurl:          ''
paginate:         5

author:
  name:           'Artem Lavrov'
  url:            https://artlavrov.github.io

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/artlavrov/artlavrov.github.io
